### ISSUE TITLE
Probleem met Datagrid

### ISSUE THREAD

**Issue by WorldwideErrors** [zvcr/1819_Code_Examples#2]
**Is het een opdracht of een los voorbeeld?**
Los voorbeeld

**Opmerkingen/Vraag**
Hoe kun je tabellen uit meerdere database tabellen in je datagrid zetten, bijvoorbeeld product en klant?

**Taal (C#/PHP/??)**
C#

**Naam**
Jeffrey van Tillo

**Klas**
IB1A

**Comment by dbergmans** [comment]
@WorldwideErrors hiervoor hebben jullie eerst de les nodig hoe je de tabellen in de database aan elkaar koppelt (met de foreign keys). Zodra jullie deze les gehad hebben, zal ik hier een voorbeeld plaatsen.
